#spring.application.name=dubbo-consumer
server: 
  context-path: /auth
  port: 8102
#应用名称
spring: 
  dubbo:
    application:
      name: auth-consumer
#注册中心地址
    protocol:
      name: dubbo
    registry:
      address: zookeeper://192.168.182.129:2181?backup=192.168.182.130:2181,192.168.182.131:2181
#调用dubbo组建扫描的项目路径
    scan: com.demo.controller
