server:
  port: 8990
#指定当前eureka客户端的注册地址
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8989/eureka,http://127.0.0.1:8991/eureka/
    register-with-eureka: false #自身 不在向eureka注册
    fetch-re gistry: false  #启动时禁用client的注册
  server:
    enable-self-preservation: false  #关闭eureka的自我保护
    eviction-interval-timer-in-ms: 10000 #超过多长时间检测eureka失败自动踢出服务

#指定应用名称
spring:
  application:
    name: eureka-server

